#!/usr/bin/env bash
# write a Bash script that configures a new Ubuntu machine to respect above requirements(this script will be run on the server itself)
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello World !" > /var/www/html/index.html
sudo service nginx start
