#!/usr/bin/env bash
# install and configure HAproxy
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y  install haproxy=2.0.\*
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 2674-web-01 18.205.109.105:80 check\n\tserver 2674-web-02 44.210.16.218:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
