#!/usr/bin/env bash
# Write a Bash script that configures a server to the above requirements (debug task)
apt-get update
apt install -y nginx
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart
