#!/usr/bin/env bash
# Write a Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
a=0
while [[ $a -le 9 ]]
do
	if [ $a = 8 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	(( a += 1 ))
done
