#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 20 and: 4 and then bad luck from China for the 4th loop 9 and then bad luck from Japan for the 9th loop 17 and then bad luck from Italy
a=1
while [[ $a -le 20 ]]
do
	case $a in
		4)
			echo $a
			echo "bad luck from China"
			;;

		9)
			echo $a
			echo "bad luck from Japan"
			;;
		17)
			echo $a
			echo "bad luck from Italy"
			;;
		*)
			echo $a
			;;
	esac
	(( a += 1 ))
done
