#!/usr/bin/env bash
#Write a Bash script that configures an Ubuntu server with the below requirements
sudo sed -i "s/127.0.0.1/127.0.0.2/g" /etc/hosts
sudo cp /etc/hosts ~/alx_hosts
echo "8.8.8.8 facebook.com" >> ~/alx_hosts
sudo cp -f ~/alx_hosts /etc/hosts
